; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "FolderViewPainter"
#define MyAppVersion "1.3.2"
#define MyAppPublisher "LesFerch"
#define MyAppURL "https://lesferch.github.io/FolderViewPainter/"
#define MyAppExeName "FolderViewPainter.exe"
#define MyEmail "lesferch@gmail.com"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId="{{70C4F9C3-6810-482B-A53D-3B87553AA3D6}"
;ArchitecturesInstallIn64BitMode=x64os
ArchitecturesInstallIn64BitMode=x64compatible
AppName={#MyAppName}
VersionInfoVersion={#MyAppVersion}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppCopyright={#MyEmail}
AppSupportURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename={#MyAppName}-Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern dynamic
SetupIconFile={#MyAppName}.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
CloseApplications=force
RestartApplications=no
ShowLanguageDialog=yes

[Files]
Source: "FolderViewPainter\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "FolderViewPainter\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "/install";

[UninstallRun]
Filename: "{app}\{#MyAppExeName}"; Parameters: "/remove"; RunOnceId: "FVPremove"

[Code]
const
  HWND_TOPMOST = -1;
  HWND_NOTOPMOST = -2;
  SWP_NOSIZE = $0001;
  SWP_NOMOVE = $0002;
  SWP_SHOWWINDOW = $0040;

function SetWindowPos(hWnd: HWND; hWndInsertAfter: HWND; X: Integer; Y: Integer; cx: Integer; cy: Integer; uFlags: UINT): BOOL;
  external 'SetWindowPos@user32.dll stdcall';

procedure InitializeWizard;
begin

  // Bring the installer window to the front, then release the topmost lock
  SetWindowPos(WizardForm.Handle, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOSIZE or SWP_NOMOVE or SWP_SHOWWINDOW);
  SetWindowPos(WizardForm.Handle, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_NOSIZE or SWP_NOMOVE);
end;

